# Generated by Django 5.1.1 on 2024-10-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0002_reviewmodel_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='product_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
